[[redirects]]
  from = "/api/*"
  to = "http://3.39.6.242:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/image-proxy/*"
to = "http://3.39.6.242:8080/:splat"
status = 200
force = true